=== apoorva240/xmlprogram/pp.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Company">
        <xs:complexType> 
            <xs:sequence>
                <xs:element name ="employee" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:integer"></xs:element>
                            <xs:element name="name" type="xs:string"></xs:element>
                            <xs:element name = "age" type="xs:int"></xs:element>
                            <xs:element name = "email" type="xs:string"></xs:element>
                            <xs:element name = "Mobnum" type="xs:integer"></xs:element>
                            <xs:element name ="designation" type = "xs:string"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        
    </xs:element>
</xs:schema>

=== apoorva240/xmlprogram/p.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="p.xsl" type="text/xsl"?>
<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pp.xsd">
    <employee>
        <id>1001</id>
        <name> Apoorva Vasishtha</name>
        <age> 30</age>
        <email>av@gmail.com</email>
        <Mobnum> 5645</Mobnum>
        <designation> CEO</designation>
    </employee>
    <employee>
        <id>1002</id>
        <name> Manish Bhambhani</name>
        <age> 60</age>
        <email>ma@gmail.com</email>
        <Mobnum> 5665</Mobnum>
        <designation> Manager</designation>

    </employee>

</Company>
